export const SPECIALIZATIONS = [
  'Mecánica General Automotriz',
  'Motor y Sistema de Transmisión',
  'Sistema Eléctrico y Electrónica Automotriz',
  'Frenos (ABS, Discos, Tambores)',
  'Suspensión y Amortiguación',
  'Sistema de Dirección (Hidráulica/Eléctrica)',
  'Aire Acondicionado y Climatización',
  'Sistema de Inyección Diesel',
  'Sistema de Inyección Gasolina (Multipunto/Directa)',
  'Cajas Automáticas y CVT',
  'Cajas Manuales y Sincronizadas',
  'Sistema de Escape y Control de Emisiones',
  'Diagnóstico Computarizado (OBD2/Scanner)',
  'Turbos y Sistemas de Sobrealimentación',
  'Sistema de Refrigeración del Motor',
  'Sistema de Combustible (Bomba, Filtros, Inyectores)',
  'Alineación, Balanceo y Geometría',
  'Cambio de Aceite y Mantenimiento Preventivo',
  'Sistema ABS y Control de Estabilidad (ESP)',
  'Sistema de Tracción 4x4 y Diferencial',
  'Airbags y Sistemas de Seguridad Pasiva',
  'Carrocería, Enderezado y Pintura',
  'Vidrios, Parabrisas y Polarizado',
  'Audio, Multimedia y Navegación GPS',
  'Alarmas, Inmovilizadores y Rastreo GPS',
  'Cerraduras Eléctricas y Control Remoto',
  'Iluminación (LED, Xenón, Halógeno)',
  'Baterías y Sistema de Carga (Alternador)',
  'Motor de Arranque y Sistema de Encendido',
  'Convertidor Catalítico y Filtro de Partículas',
  'Sistema de Embrague (Hidráulico/Mecánico)',
  'Correas de Distribución y Cadenas',
  'Sistema de Lubricación del Motor',
  'Juntas, Retenes y Sellos Automotrices',
  'Neumáticos y Válvulas de Presión (TPMS)',
  'Sistema de Freno de Mano Electrónico',
  'Conversión a GNC (Gas Natural Comprimido)',
  'Conversión a GLP (Gas Licuado de Petróleo)',
  'Vehículos Híbridos (Motor Eléctrico + Combustión)',
  'Vehículos Eléctricos (100% Electric)',
  'Baterías de Alto Voltaje para Híbridos/Eléctricos',
  'Sistema de Regeneración de Energía',
  'Inspección Técnica Vehicular',
  'Limpieza de Inyectores y Válvulas',
  'Rectificación de Motores',
  'Soldadura Automotriz (MIG/TIG)',
  'Tapicería y Restauración de Interiores',
  'Tunning y Preparación Deportiva',
  'Modificaciones y Personalización',
  'Vehículos Pesados y Camiones',
];

export const NATIONALITIES = [
  'Chilena',
  'Argentina',
  'Peruana',
  'Boliviana',
  'Colombiana',
  'Ecuatoriana',
  'Venezolana',
  'Brasileña',
  'Paraguaya',
  'Uruguaya',
  'Mexicana',
  'Cubana',
  'Dominicana',
  'Haitiana',
  'Española',
  'Italiana',
  'Francesa',
  'Alemana',
  'Portuguesa',
  'Estadounidense',
  'Canadiense',
  'China',
  'Japonesa',
  'Coreana',
  'Otra',
];
